main/routes.py
from flask import render_template, Blueprint, request
from models import Transaction

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('homepage.html', title = 'Home')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

transactions/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import  current_user, login_required
from extensions import db, bcrypt
from models import User, Transaction
from transactions.forms import (WithdrawForm, ProductionForm, BorrowForm  )

transactions = Blueprint('transactions', __name__)

@transactions.route("/withdraw", methods=['GET', 'POST'])
@login_required
def withdraw():
    form = WithdrawForm()
    if form.validate_on_submit():
        withdraw_amount = form.withdraw_amount.data

        # Check if the withdrawal amount exceeds the wallet balance
        if withdraw_amount > current_user.wallet_balance:
            flash(f"Insufficient funds! You only have Ksh. {current_user.wallet_balance} in your wallet.", 'danger')
            return redirect(url_for('transactions.withdraw'))

        # Create a new transaction for the withdrawal
        transaction = Transaction(
            user_id=current_user.id, 
            transaction_type='withdrawal',
            description=form.description.data, 
            withdraw_amount=withdraw_amount
        )
        
        # Update the wallet balance after the withdrawal
        current_user.wallet_balance -= withdraw_amount

        # save to the db
        db.session.add(transaction)
        db.session.commit()

        flash('Withdrawal successful!', 'success')
        return redirect(url_for('transactions.withdraw'))

    return render_template('withdraw.html', title='Withdraw', form=form)


@transactions.route("/production", methods=['GET', 'POST'])
@login_required
def production():
    form = ProductionForm()
    if form.validate_on_submit():
        transaction = Transaction(user_id=current_user.id, 
                                 transaction_type=form.transaction_type.data, 
                                 description=form.description.data, 
                                 product=form.product.data,
                                 kgs=form.kgs.data,
                                 cost_per_kg = form.cost_per_kg.data)
        
        # Calculate total produced using the Transaction model's method
        transaction.total_amount = transaction.calculate_amount_from_product()
        
        db.session.add(transaction)
        db.session.commit()
        
        # Update the user's credit limit
        current_user.update_credit_limit()

        flash('Production successful!', 'success')
        return redirect(url_for('transactions.production'))
    return render_template('production.html', title='Production', form=form)

@transactions.route("/borrow", methods=['GET', 'POST'])
@login_required
def borrow():
    form = BorrowForm()
    if form.validate_on_submit():
        borrow_amount = form.borrowed_amount.data

        try:
            # Create a new transaction instance
            transaction = Transaction(
                user_id=current_user.id,
                description=form.description.data,
                borrowed_amount=borrow_amount
            )
            
            # Process borrowing and ensure it checks the credit limit and wallet balance
            transaction.process_borrowing(user=current_user, borrow_amount=borrow_amount)

            # Add the transaction to the session and commit
            db.session.add(transaction)
            db.session.commit()

            # Provide feedback to the user
            flash(f'Borrow successful! Ksh. {borrow_amount} has been added to your wallet.', 'success')
            return redirect(url_for('transactions.borrow'))

        except ValueError as e:
            flash(str(e), 'danger')

    return render_template('borrow.html', title='Borrow', form=form)

@transactions.route("/transactions")
@login_required
def transactions_history():
    transactions = Transaction.query.filter_by(user_id=current_user.id).all()
    return render_template('dashboard.html', transactions=transactions)

@transactions.route("/transaction/<int:transaction_id>")
@login_required
def transaction(transaction_id):
    transaction = Transaction.query.get_or_404(transaction_id)
    return render_template('transaction.html', transaction=transaction)

users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from extensions import db, bcrypt
from models import User, Transaction
from users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.national_id = form.national_id.data
        current_user.phone = form.phone.data
        current_user.address = form.address.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.username.data = current_user.username
        form.national_id.data = current_user.national_id
        form.phone.data = current_user.phone
        form.address.data = current_user.address
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    transactions = Transaction.query.filter_by(creator=user)\
        .order_by(Transaction.datransaction_date.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_transactions.html', transactions=transactions, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.first_name.label(class="form-control-label") }}

                    {% if form.first_name.errors %}
                        {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.first_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.last_name.label(class="form-control-label") }}

                    {% if form.last_name.errors %}
                        {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.last_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.last_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.national_id.label(class="form-control-label") }}

                    {% if form.national_id.errors %}
                        {{ form.national_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.national_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.national_id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.phone.label(class="form-control-label") }}

                    {% if form.phone.errors %}
                        {{ form.phone(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.phone.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.phone(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

templates/homepage.html
{% extends "layout.html" %}
{% block content %}
    <div class="main-content">
        <div class="homepage-cards">
            <div class="card-info">
                <h4>Some title description</h4>
                <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean bibendum ante laoreet posuere tincidunt. Maecenas eget sollicitudin est. Proin pulvinar nibh vitae ante auctor, vel iaculis sapien fringilla. Nullam congue pharetra arcu vitae malesuada. Sed orci eros, tristique a mattis quis, laoreet sed sapien. Aliquam vel velit eros. Integer placerat sapien vel posuere laoreet. Morbi tempor commodo lectus eu varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin a risus vel quam dignissim iaculis. Aliquam erat volutpat.</p>
                <button>Learn More</button>
            </div>
            <div class="card-pic">
                <img src="./static/images/tea.png" alt="tea" />
            </div>
            <div class="card-pic">
                <img src="./static/images/dairycows.jpg" alt="milk-cows" />
            </div>
            <div class="card-info">
                <h4>Some title description</h4>
                <p>Aenean metus ex, rutrum ut dictum vitae, ultrices a tellus. Duis mollis tristique enim in eleifend. Ut aliquet nunc pretium, facilisis erat at, fringilla dolor. Aliquam mattis leo magna, sit amet aliquet nulla hendrerit id. Cras quis ante quam. Pellentesque sit amet efficitur justo. Nam condimentum, metus sit amet molestie pulvinar, eros leo iaculis dolor, a venenatis est velit sed tellus. Nulla mi tellus, tempor quis ex sed, tincidunt vulputate odio. Sed tellus elit, malesuada id tempor sit amet, viverra id erat. Nulla non tortor vitae ex pulvinar viverra eu eu odio. Maecenas blandit justo eget egestas dignissim. Morbi dictum urna nec metus fermentum elementum rhoncus et mauris. Integer consectetur aliquet blandit. Maecenas porta augue eget orci fringilla porttitor.</p>
                <button>Learn More</button>
            </div>
            <div class="card-info">
                <h4>Some title description</h4>
                <p>Pellentesque eget est a felis elementum commodo. Maecenas lobortis turpis eget quam pulvinar, non gravida odio pharetra. Aenean nisi mi, rutrum sit amet mi non, vulputate faucibus risus. Nam a finibus erat. Curabitur suscipit erat sit amet velit feugiat, sed mattis augue efficitur. Phasellus faucibus risus ut velit pellentesque semper. Integer dignissim rutrum congue. Sed rutrum est non tempus ultricies. In consequat cursus libero dapibus congue. In porta consectetur semper. Sed orci risus, efficitur ut libero a, fermentum faucibus sapien.</p>
                <button>Learn More</button>
            </div>
            <div class="card-pic">
                <img src="./static/images/Maize.jpg" alt="maize" />
            </div>
            <div class="card-pic">
                <img src="./static/images/farm_aerial.jpeg" alt="farm-aerial-view" />
            </div>
            <div class="card-info">
                <h4>Some title description</h4>
                <p>Phasellus eu metus vel quam feugiat fringilla id vel quam. Sed maximus tellus rhoncus, elementum arcu id, iaculis nibh. Fusce convallis ante non consectetur mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque at semper quam. Maecenas eget risus nibh. Etiam vitae urna tincidunt, dictum mauris eget, dictum massa. Nulla facilisi. Nunc vel tellus nec eros pulvinar porta. Praesent ut viverra diam. Quisque faucibus, lacus quis pharetra placerat, nisi risus porttitor odio, at tempus arcu felis tincidunt risus. Etiam accumsan libero urna, ut molestie sapien suscipit et.</p>
                <button>Learn More</button>
            </div>
        </div>
        <div class="call-to-action">
            <h2>Join the movement</h2>
            <p>If you would like to find out more about PesaFresh credits, find out how much you qualify for by taking the first step</p>
            <a href="{{ url_for('users.register') }}">
                <button>Register with us</button>
            </a>            
        </div>
    </div>

{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>PesaFresh - {{ title }}</title>
    {% else %}
        <title>PesaFresh</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <a class="navbar-brand" href="/">PesaFresh</a>
        <div class="container">
         
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="search">
              <input type="text" placeholder="Search..." />
            </div>
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('transactions.transactions_history') }}">Dashboard</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
    <footer class="footer-container">
      <!-- start of the top footer  -->
      <div class="footer-top">
          <div class="footer-top-column">
            <div class="footer-logo">
              <img src="./static/images/image.png" alt="logo" />
            </div>
          <div class="footer-subscribe">
                  <h5 class="footer-subscribe-title">Subscribe to our newsletter and get 15% off your first credit.</h5>
                  <div>
                      <form class="footer-subscribe-form">
                        <input type="email" class="footer-subscribe-input" placeholder="Your Email" />
                        <button class="footer-subscribe-button" type="submit">Subscribe</button>
                      </form>
                      <div class="footer-subscribe-disclaimer">
                        <input type='checkbox' class="footer-checkbox" defaultValue={true}/>
                        <p class="footer-subscribe-agreement">I agree to receive PesaFresh newsletters</p>
                      </div>
                  </div>
              </div>
              <div class="footer-social-row">
                <ul class="footer-social-list">
                  <FontAwesomeIcon icon={faFacebook} /> 
                  <FontAwesomeIcon icon={faXTwitter} />
                  <FontAwesomeIcon icon={faInstagram} />
                  <FontAwesomeIcon icon={faLinkedin} />
                </ul>
              </div>
          </div>
              <div class="footer-top-column">
                      <div class="footer-links-row">
                          <ul class="footer-links-list">
                              <li><a class="footer-link" href="/#">About Us</a></li>
                              <li><a class="footer-link" href="/#about-us-mission-vision">Team </a></li>
                              <li><a class="footer-link" href="/#">Blog</a></li>
                              <li><a class="footer-link" href="/#">Terms of Use</a></li>
                          </ul>
                      </div>
                      <div class="footer-address">
                       <div class="street">
                        <FontAwesomeIcon icon={faLocationDot} />
                        <p>123 Street, Nairobi, Kenya</p>
                       </div>
                       <div class="phone">
                        <FontAwesomeIcon icon={faPhone} />
                        <p>+254 000 000</p>
                       </div>
                       <div class="email">
                        <FontAwesomeIcon icon={faEnvelope} />
                        <p>info@pesafresh.com</p>
                       </div>
                      </div>
              </div>
              <div class="footer-top-column">
                  <h5 class="footer-links-title">Need Help?</h5>
                  <ul class="footer-links-list">
                      <li><a class="footer-link" href="/#">Contact Us</a></li>
                      <li><a class="footer-link" href="/#">FAQs</a></li>
                      <li><a class="footer-link" href="/#">Offers &amp; Kits</a></li>
                      <li><a class="footer-link" href="/#">Get the app</a></li>
                  </ul>
              </div>
      </div>
      <!-- start of the bottom footer -->
    <div class="footer-bottom">
          <div class="footer-bottom-column">
              <div class="footer-bottom-left">
                  <p class="footer-bottom-text">© 2024 copyright by <a class="footer-bottom-link" href="/#">PesaFresh.com</a></p>
              </div>
          </div>
          <div class="footer-bottom-column">
                  <ul class="footer-bottom-right">
                      <li class="footer-bottom-item"><a href="/#" class="footer-bottom-link">Privacy &amp; Policy</a></li>
                      <li class="footer-bottom-item"><a href="/#" class="footer-bottom-link">FAQs</a></li>
                  </ul>
          </div>
    </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/transaction.html
{% extends "layout.html" %}
{% block content %}
    <h1>One transaction</h1>
{endblock content}

templates/user_transactions.html
{% extends "layout.html" %}
{% block content %}
    <h2>User transactions</h2>
{% endblock % }